name: frontend
description: 便携式健康管理系统Flutter前端
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.5
  dio: ^5.4.3+1
  shared_preferences: ^2.2.2
  web_socket_channel: ^2.4.0
  permission_handler:  ^11.3.1  # 使用最新版本
  intl: ^0.17.0 # 时间格式化
  charts_flutter: ^0.12.0 # 简易数据图表
  fl_chart: ^1.2.0
  url_strategy: ^0.2.0 # 用于去除URL中的#号

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/